/* myTraining — módulo extraído de index.html (Fase 0). */
import { addMedia } from './media.js';
import { esc } from './state.js';

/* ═══════════ FICHA TÉCNICA (estilo personal trainer) ═══════════ */
const GUIDE={
  "Supino reto":{setup:"Deita-te no banco com os olhos sob a barra. Pés firmes no chão, retrai e deprime as escápulas (peito para fora), cria um ligeiro arco lombar natural.",exec:"Pega a barra um pouco mais larga que os ombros. Desce controlado até tocar ao meio do peito (mamilos), cotovelos a ~45–75° do tronco. Empurra para cima e ligeiramente para trás até estender os cotovelos.",tips:["Não abras os cotovelos a 90° — protege os ombros.","Mantém as escápulas retraídas durante todo o movimento.","Antebraços sempre verticais no ponto baixo.","Não faças ressalto da barra no peito."],breath:"Inspira ao descer, expira ao empurrar."},
  "Supino inclinado":{setup:"Banco a 30–45°. Mesmo set-up do supino: escápulas retraídas, pés firmes, peito para fora.",exec:"Desce a barra/halteres até à parte alta do peito (clavículas). Empurra para cima sem bloquear bruscamente.",tips:["Inclinação alta demais (>45°) transfere o esforço para os ombros.","Cotovelos ligeiramente recolhidos, não totalmente abertos.","Controla a descida 2–3 segundos."],breath:"Inspira ao descer, expira ao subir."},
  "Crucifixo":{setup:"Deitado (banco) ou em pé (cabos). Halteres/punhos alinhados sobre o peito, ligeira flexão fixa nos cotovelos.",exec:"Abre os braços em arco amplo como se abraçasses uma árvore, sentindo o alongamento no peito. Fecha contraindo o peito, sem bater os halteres.",tips:["O cotovelo mantém o MESMO ângulo todo o movimento — não é um supino.","Não desças demais para não stressar o ombro.","Foca a contração no peito, não nos braços."],breath:"Inspira ao abrir, expira ao fechar."},
  "Paralelas":{setup:"Agarra as barras, braços estendidos, corpo suspenso. Inclina o tronco ligeiramente à frente para ativar o peito.",exec:"Desce dobrando os cotovelos até sentires alongamento no peito (~90°). Empurra de volta até estender.",tips:["Tronco vertical = mais tríceps; inclinado à frente = mais peito.","Não desças abaixo do confortável para o ombro.","Evita balançar — movimento controlado."],breath:"Inspira ao descer, expira ao subir."},
  "Tríceps corda":{setup:"De frente para o cabo alto, corda na pega. Cotovelos colados ao tronco, tronco ligeiramente inclinado.",exec:"Estende os cotovelos para baixo e, no final, abre as pontas da corda afastando-as. Volta controlado sem deixar os cotovelos saírem do sítio.",tips:["Só o antebraço se move — cotovelos FIXOS ao corpo.","Abre a corda no fim para contração máxima.","Não uses o peso do corpo para empurrar."],breath:"Expira ao estender, inspira ao voltar."},
  "Tríceps testa":{setup:"Deitado no banco, barra EZ acima do peito, braços estendidos. Cotovelos apontados ao teto.",exec:"Dobra só os cotovelos, descendo a barra até perto da testa/atrás da cabeça. Estende de volta.",tips:["Os cotovelos ficam quietos, apontados ao teto — não os abras.","Desce atrás da cabeça para mais alongamento do tríceps.","Controla a descida para proteger os cotovelos."],breath:"Inspira ao descer, expira ao estender."},
  "Puxada frente":{setup:"Sentado na puxada, coxas presas, pega ampla. Peito para fora, ligeira inclinação do tronco para trás.",exec:"Puxa a barra até à parte alta do peito/queixo, levando os cotovelos para baixo e para trás. Contrai as costas. Sobe controlado até estender.",tips:["Puxa com os cotovelos, não com as mãos.","Não puxes atrás da nuca — risco para o ombro.","Não uses balanço do tronco para puxar.","Sente as omoplatas a juntar-se."],breath:"Expira ao puxar, inspira ao subir."},
  "Remada":{setup:"Tronco inclinado ~45°, costas retas e firmes, joelhos ligeiramente fletidos, barra a pender dos braços.",exec:"Puxa a barra em direção ao umbigo/baixo abdómen, juntando as escápulas. Desce controlado.",tips:["Costas SEMPRE retas — nunca curvar a lombar.","Puxa para a barriga, não para o peito.","Aperta as omoplatas no topo.","Evita levantar o tronco a cada repetição."],breath:"Expira ao puxar, inspira ao descer."},
  "Remada unilateral":{setup:"Um joelho e uma mão no banco, costas paralelas ao chão e retas. Haltere a pender da mão livre.",exec:"Puxa o haltere para o lado da anca, cotovelo junto ao corpo, levando-o para trás. Desce controlado com alongamento.",tips:["Costas paralelas ao chão e direitas.","Não rodes o tronco para puxar mais peso.","Cotovelo viaja junto ao corpo, para trás."],breath:"Expira ao puxar, inspira ao descer."},
  "Pulldown":{setup:"Sentado, pega fechada ou ampla conforme variação. Peito para fora, tronco quase vertical.",exec:"Puxa com as costas levando os cotovelos junto ao corpo para baixo. Contrai e sobe controlado.",tips:["Iniciar o movimento pelas escápulas (deprimir), não pelos bíceps.","Evita inclinar muito o tronco para trás.","Amplitude completa em cima."],breath:"Expira ao puxar, inspira ao subir."},
  "Rosca direta":{setup:"Em pé, barra/halteres com pega supinada (palmas para cima), cotovelos colados ao tronco.",exec:"Flete os cotovelos subindo o peso até à contração máxima do bíceps. Desce controlado até estender.",tips:["Cotovelos FIXOS ao lado do corpo — não os mandes à frente.","Sem balanço dos ombros/lombar.","Controla a descida (fase excêntrica) 2s.","Aperta o bíceps no topo."],breath:"Expira ao subir, inspira ao descer."},
  "Rosca alternada":{setup:"Em pé, um haltere em cada mão, pega neutra (palmas para dentro).",exec:"Sobe um haltere de cada vez, rodando o pulso para supinado a meio do movimento. Pausa no topo, desce controlado.",tips:["Roda o pulso ao subir para ativar mais o bíceps.","Pausa de 1s no topo.","Cotovelo quieto ao lado do corpo."],breath:"Expira ao subir, inspira ao descer."},
  "Agachamento":{setup:"Barra apoiada no trapézio (não no pescoço), pés à largura dos ombros, pontas ligeiramente para fora. Peito para cima, core contraído, olhar em frente.",exec:"Desce empurrando a anca para trás e dobrando os joelhos, como se te sentasses. Desce até as coxas ficarem ~paralelas ao chão. Sobe empurrando o chão com os calcanhares.",tips:["Joelhos acompanham a direção das pontas dos pés — não para dentro.","Costas direitas, peito para cima durante todo o movimento.","Calcanhares sempre no chão.","Desce com controlo, não caias."],breath:"Inspira ao descer (e segura o core), expira ao subir."},
  "Leg press":{setup:"Costas e glúteos bem apoiados no encosto, pés à largura dos ombros na plataforma.",exec:"Desce a plataforma dobrando os joelhos até ~90°. Empurra de volta sem bloquear bruscamente os joelhos.",tips:["Nunca bloqueies os joelhos no topo.","A lombar não deve descolar do encosto.","Pés mais altos = mais glúteo/isquios; mais baixos = mais quadríceps."],breath:"Inspira ao descer, expira ao empurrar."},
  "Stiff":{setup:"Em pé, barra/halteres à frente das coxas, joelhos ligeiramente fletidos (fixos), costas retas.",exec:"Empurra a anca para trás descendo o peso junto às pernas, até sentires alongamento nos isquiotibiais. Volta contraindo glúteos e isquios.",tips:["O movimento é da ANCA, não da lombar — não curves as costas.","Joelhos quase fixos, só ligeiramente dobrados.","Barra desliza junto às pernas.","Desce até onde a flexibilidade permitir sem curvar."],breath:"Inspira ao descer, expira ao subir."},
  "Mesa flexora":{setup:"Deitado de barriga para baixo na máquina, rolo apoiado acima dos calcanhares (não nos gémeos).",exec:"Flete os joelhos puxando o rolo em direção aos glúteos. Contrai os isquiotibiais no topo, desce controlado.",tips:["Não levantes a anca do apoio.","Contrai no topo 1s.","Desce devagar (fase excêntrica)."],breath:"Expira ao fletir, inspira ao descer."},
  "Cadeira extensora":{setup:"Sentado, costas apoiadas, rolo acima dos tornozelos.",exec:"Estende os joelhos elevando o rolo até à extensão quase completa. Pausa 1s, desce controlado.",tips:["Não dês solavancos — controla.","Pausa no topo para máxima contração do quadríceps.","Não bloqueies violentamente."],breath:"Expira ao estender, inspira ao descer."},
  "Panturrilha":{setup:"Em pé (ou na máquina), pontas dos pés num apoio, calcanhares livres.",exec:"Eleva os calcanhares o máximo possível (ponta dos pés), aguenta 2s no topo. Desce até sentir alongamento.",tips:["Amplitude COMPLETA: sobe ao máximo, desce ao máximo.","Pausa de 2s em cima.","Sem ressaltos rápidos — o gémeo responde a tempo sob tensão."],breath:"Expira ao subir, inspira ao descer."},
  "Desenvolvimento":{setup:"Sentado ou em pé, halteres/barra à altura dos ombros, core contraído, costas neutras.",exec:"Empurra o peso acima da cabeça até estender os braços. Desce controlado até aos ombros.",tips:["Não arqueies a lombar — contrai o abdómen.","Não bloqueies bruscamente os cotovelos.","Barra/halteres alinhados sobre a cabeça, não à frente."],breath:"Expira ao empurrar, inspira ao descer."},
  "Elevação lateral":{setup:"Em pé, halteres ao lado do corpo, ligeira flexão dos cotovelos (fixa).",exec:"Eleva os braços para os lados até à altura dos ombros, liderando com os cotovelos. Desce controlado.",tips:["Polegares ligeiramente para baixo (como verter água de um jarro).","Não passes muito acima da linha dos ombros.","Sem balanço — se precisas de impulso, baixa o peso.","Movimento lento, sobretudo na descida."],breath:"Expira ao subir, inspira ao descer."},
  "Posterior ombro":{setup:"Tronco inclinado à frente (sentado ou em pé), halteres a pender, ligeira flexão dos cotovelos.",exec:"Abre os braços para trás como asas, apertando o deltóide posterior e as omoplatas. Desce controlado.",tips:["Inclina bem o tronco à frente.","Foca o deltóide posterior, não o trapézio.","Peso leve — é um músculo pequeno."],breath:"Expira ao abrir, inspira ao fechar."},
  "Face pull":{setup:"Cabo à altura do rosto, corda na pega, braços estendidos à frente.",exec:"Puxa a corda em direção à cara, abrindo as mãos e levando os cotovelos altos e para trás. Contrai os romboides.",tips:["Cotovelos altos durante todo o movimento.","Puxa para a testa/cara, não para o peito.","Ótimo para a saúde do ombro e postura."],breath:"Expira ao puxar, inspira ao voltar."},
  "Prancha":{setup:"Apoio nos antebraços e pontas dos pés, cotovelos sob os ombros. Corpo em linha reta da cabeça aos calcanhares.",exec:"Mantém a posição contraindo abdómen e glúteos, sem deixar a anca subir ou descer.",tips:["Não deixes a lombar ceder (anca a cair).","Não levantes o rabo.","Contrai glúteos e abdómen ativamente.","Respira normalmente — não prendas o ar."],breath:"Respiração contínua e controlada."},
  "Abdominal":{setup:"Deitado de costas, joelhos fletidos, mãos atrás da cabeça (sem puxar) ou no peito.",exec:"Enrola a coluna elevando os ombros do chão, contraindo o abdómen. Desce controlado sem relaxar totalmente.",tips:["Não puxes o pescoço com as mãos.","O movimento é enrolar, não levantar com o pescoço.","Expira com força ao subir para contrair mais.","Controla a descida."],breath:"Expira ao subir, inspira ao descer."},
  "Levantamento terra":{setup:"Pés à largura da anca, barra sobre o meio do pé (junto às canelas). Anca para trás, costas RETAS, peito para cima, escápulas sobre a barra.",exec:"Empurra o chão com os pés levantando a barra junto às pernas, estendendo anca e joelhos em simultâneo. Em cima, fica direito (sem hiperextender). Desce controlado pelo mesmo caminho.",tips:["Costas SEMPRE retas — nunca curvar a lombar (lesão grave).","A barra desliza junto ao corpo.","Empurra o chão, não 'puxes' com as costas.","Anca e ombros sobem ao mesmo tempo.","Aperta o core antes de cada repetição."],breath:"Inspira e segura o core antes de subir, expira em cima."},
  "Supino":{setup:"Deita-te com olhos sob a barra, escápulas retraídas, pés firmes, ligeiro arco lombar.",exec:"Desce a barra ao meio do peito com cotovelos a ~45–75°. Empurra até estender.",tips:["Escápulas retraídas todo o movimento.","Antebraços verticais no ponto baixo.","Sem ressalto no peito."],breath:"Inspira ao descer, expira ao empurrar."},
  "Puxada alta":{setup:"Sentado na puxada, pega ampla, peito para fora, ligeira inclinação para trás.",exec:"Puxa a barra ao peito com os cotovelos a descer junto ao corpo. Contrai as costas, sobe controlado.",tips:["Puxa com as costas, cotovelos para baixo.","Não atrás da nuca.","Sem balanço do tronco."],breath:"Expira ao puxar, inspira ao subir."},
  "Agachamento goblet":{setup:"Segura um haltere/kettlebell junto ao peito com as duas mãos. Pés à largura dos ombros, pontas ligeiramente para fora.",exec:"Desce mantendo o peito alto e os cotovelos por dentro dos joelhos. Sobe empurrando pelos calcanhares.",tips:["Peito alto, tronco vertical.","Joelhos abertos, a acompanhar os pés.","Ótimo para aprender a técnica de agachamento.","Calcanhares no chão."],breath:"Inspira ao descer, expira ao subir."},
  "Braços":{setup:"Superset: alterna bíceps e tríceps sem descanso entre os dois.",exec:"Faz uma série de bíceps (rosca) seguida imediatamente de uma de tríceps (extensão). Descansa só no fim do par.",tips:["Mantém a técnica mesmo com fadiga.","Cotovelos fixos em ambos.","Controla as descidas."],breath:"Expira no esforço, inspira no retorno."},
  "Core":{setup:"Varia entre prancha, hollow body, dead bug, russian twist conforme o dia.",exec:"Executa cada exercício com o abdómen contraído e a coluna controlada, sem compensar com a lombar.",tips:["Qualidade > quantidade.","Lombar protegida (não arquear).","Respira de forma controlada.","Varia os estímulos."],breath:"Respiração controlada e contínua."},
  "Cardio leve":{setup:"Escolhe a modalidade (passadeira, bicicleta, elíptica, remo). Postura ereta.",exec:"Mantém um ritmo de Zona 2: consegues conversar mas com algum esforço (FC ~60–70% da máxima), 20–30 min.",tips:["Se não consegues falar, abranda.","Mantém a postura direita.","Ideal para recuperação e saúde cardiovascular."],breath:"Respiração ritmada e confortável."},
  "Descanso ativo":{setup:"Dia de recuperação. Mobilidade, alongamentos, yoga suave ou caminhada.",exec:"Movimento leve para promover circulação e recuperação, sem fadiga.",tips:["Não treines com intensidade.","Foca mobilidade das zonas mais tensas.","Hidrata e dorme bem — é aqui que o músculo cresce."],breath:"Respiração relaxada e profunda."}
};
function openInfo(name){
  const g=GUIDE[name];
  const body=document.getElementById('infoBody');
  if(g){
    body.innerHTML=`
      <div class="info-x-name">${esc(name)}</div>
      <div class="info-sec"><div class="info-h">🎯 Posição inicial</div><p>${esc(g.setup)}</p></div>
      <div class="info-sec"><div class="info-h">▶️ Execução</div><p>${esc(g.exec)}</p></div>
      <div class="info-sec"><div class="info-h">✅ Postura & dicas</div><ul>${g.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>
      <div class="info-sec"><div class="info-h">🫁 Respiração</div><p>${esc(g.breath)}</p></div>
      <div class="info-add"><button class="nbtn" onclick="closeInfo();addMedia('${name.replace(/'/g,"\\'")}')">＋ Adicionar a minha demo (link)</button></div>`;
  } else {
    body.innerHTML=`<div class="info-x-name">${esc(name)}</div><p class="ndisc">Sem ficha técnica para este exercício.</p>`;
  }
  document.getElementById('infoBg').classList.add('show');
}
function closeInfo(){ document.getElementById('infoBg').classList.remove('show'); }

export { GUIDE, openInfo, closeInfo };
